# Generated by Django 5.2.4 on 2025-07-27 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_category_event_is_featured_event_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_featured',
            new_name='is_published',
        ),
    ]
