# Generated by Django 5.2.4 on 2025-07-27 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_is_featured_event_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.CharField(choices=[('Festival', 'Festival'), ('Party', 'Party'), ('Seminar', 'Seminar'), ('Competition', 'Competition')], default='Festival', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
