# Generated by Django 5.2.4 on 2025-07-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_booking_category_booking_date_booking_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_seats',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
